FROM node:24-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable
RUN corepack install --global pnpm@10.15.1
RUN corepack use pnpm@10.15.1

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml* ./
COPY turbo.json ./
COPY apps/content-management/package.json apps/content-management/

RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

COPY apps/content-management apps/content-management/

EXPOSE 3000
WORKDIR /app/apps/content-management
CMD [ "pnpm", "exec", "nest", "start", "--watch" ]
